title: "Interim, in-market packing report - 2025"

date: 07/30/2025
date-format: long

bibliography: References.bib
csl: apa.csl

mainfont: Geograph
monofont: Geograph
sansfont: Geograph

prefer-html: true
always_allow_html: yes
  


